globals:
  device: 'cuda'
  sample_cpu: true
  n_thread: 1
  n_parallel: 8
  mlp_arch: [512, 512]

skill:
  name: 'metra'
  lr: 1e-4
  dim_option: 2
  discrete: false
  unit_length: true
  device: ${globals.device}
  dual_reg: true
  dual_slack: 1e-3
  dual_dist_name: 'one'
  dual_dist: null
  dual_lam: 30
  target_traj_encoder: 0.
  slot_pooler:
    name: Fetcher
    kwargs: {}

rl_algo:
  name: 'SAC'
  lr: 1e-4
  wd: 0.
  tau: 5e-3
  discount: '0.99'
  device: ${globals.device}
  policy:
    name: 'option_policy'
    dim_option: ${skill.dim_option}
    distribution_parameterization: TwoHeads
    normal_distribution_cls: TanhNormal
    init_std: 1.
    hidden_sizes: ${globals.mlp_arch}
    hidden_nonlinearity: Tanh
  critics:
    hidden_sizes: ${globals.mlp_arch}
    hidden_nonlinearity: ReLU
  alpha:
    value: 1e-2

replay_buffer:
  common:
    min_transitions: 10000
    max_transitions: 300000
    batch_size: 256

trainer_args:
  n_parallel: 4
  collection_steps: 1600
  n_epochs: 100_000
  trans_optimization_epochs: 200
  transitions_before_training: 10_000
  log_frequency: 50_000
  eval_frequency: 250_000