globals:
  encoder: 'cnn'

env:
  name: "dmc_quadruped"
  normalizer_type: "squashed"
  frame_stack: 3
  max_path_length: 200
  env_kwargs: null

trainer_args:
  trans_optimization_epochs: 200

replay_buffer:
  skill:
    min_transitions: null
    max_transitions: 4_800
    batch_size: 256
  common:
    max_transitions: 300000

skill:
  name: "metra"
  discrete: false
  dim_option: 4